### ISSUE TITLE
Allow main report to list all attempts instead of just one per user.

### ISSUE THREAD

**Issue by adamfranco** [middlebury/moodle-mod_adaptivequiz#16]
This will allow easier reporting when the same test is used for entrance and exit exams.

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test? 
khalid.kabchi@gmail.com

**Comment by adamfranco** [comment]
Thank you for submitting this issue. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
