### ISSUE TITLE
fetchquestion::fetch_questions() doesn't start its search directionally.

### ISSUE THREAD

**Issue by adamfranco** [middlebury/moodle-mod_adaptivequiz#2]
Question search should bias toward more difficult questions when the last question was correct or easier questions when the last question was wrong. Currently it is always starting its search in the harder direction.

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test? 
khalid.kabchi@gmail.com

**Comment by adamfranco** [comment]
This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
