### ISSUE TITLE
Image path corrupted by +1 

### ISSUE THREAD

**Issue by edequal** [middlebury/moodle-mod_adaptivequiz#28]
The images are not visible, and the pathway seems to get corrupted on the way from draftfile.php to pluginfile.php

E.G; the image is visible on editing mode to the teacher, but when the students starts an attempt, the student doesnt see the image, but if i change the pathway i.e change the folder name. (Have -1 the original folder number) The image appears.

![1](https://cloud.githubusercontent.com/assets/5813179/6146482/12af32aa-b20f-11e4-94f4-b7c7400a7373.JPG)
![2](https://cloud.githubusercontent.com/assets/5813179/6146483/12b2931e-b20f-11e4-908a-3ddecfe9dc1c.JPG)
![3](https://cloud.githubusercontent.com/assets/5813179/6146484/12b5a4dc-b20f-11e4-9f1e-feac5bba99c1.JPG)

**Comment by adamfranco** [comment]
As with #31, this issue should now be resolved in the 1.2.2 release by the change in 4fe647aba19a4f78496eb6babc9b254558266fa7. Please test and reopen if this issue persists.
