### ISSUE TITLE
Compatibility with Moodle 3.1

### ISSUE THREAD

**Issue by polothy** [middlebury/moodle-mod_adaptivequiz#41]
Several unit tests fail due to Moodle tag API changes.  Need to replace [old tag API](https://github.com/moodle/moodle/blob/MOODLE_31_STABLE/tag/upgrade.txt) and update XML data fixtures.

Is a release for 3.1 planned anytime soon?

**Comment by adamfranco** [comment]
Thanks for the report, @mrmark. We're still running Moodle 2.8 and our development team is currently focused on other projects, so we won't be able to provide a quick turn around ourselves. That said, we'd be happy to quickly review/test/merge one or more pull requests with the needed changes.

**Comment by semteacher** [comment]
I have submitted a pull-request which may solve part of that problems
https://github.com/middlebury/moodle-mod_adaptivequiz/pull/44
Also, I have unit-test fix which reduce number of failures and warnings (but do not solve all).
https://github.com/semteacher/moodle-mod_adaptivequiz/tree/apply-mod_quiz_workflov2-unittests
If it will be helpful - I can create the pull-request too

**Comment by adamfranco** [comment]
Thanks, I've merged your PR!
