### ISSUE TITLE
Immediate feedback (enchancement)

### ISSUE THREAD

**Issue by semteacher** [middlebury/moodle-mod_adaptivequiz#43]
Hi, @adamfranco 
I have read in previous topics that you cannot pay a lot of attention to this plugin. So, I have tried to make some customization of it. I got task to implement feature like "immediate feedback" in general quiz module:
- student got, and submit question answer (Submit button)
- instead of new question - he returned to same question page where is shown is his answer was correct or not (and show correct answer - depend to other settings).
- to move forward to the next question - student must press "next" button
Could you provide me some recommendations / hints / docs about how this could be implemented?

**Comment by adamfranco** [comment]
Thanks for the interest. I would think that to achieve such a result, the procedural code in [`attempt.php`](https://github.com/middlebury/moodle-mod_adaptivequiz/blob/MOODLE_29_STABLE/attempt.php) would need to be updated to check if the quiz was set to "immediate feedback mode" and then not move on to calculating the next level of difficulty unless the "Next" button's value was in the submission. This looks like it partially occurs around lines [195-248](https://github.com/middlebury/moodle-mod_adaptivequiz/blob/MOODLE_29_STABLE/attempt.php#L195-L248). I'm not the original author of this particular code, so I unfortunately don't have any deeper insight into the sequencing of the actions in this script.

**Comment by semteacher** [comment]
Thanks for answer and hint. I have tried some code experiments. Look like that it will be not easy - to provide this modifications...
I need, if possible, one additional hint - just about module usage "as is":
- teacher has created one official tag: https://www.screencast.com/t/sjQvMqiWM
- he assign official and additional tags to question, like this https://www.screencast.com/t/Ae6esKsg
- however, during attempt we got next: https://www.screencast.com/t/sjTyCpbOBLIQ
all question marked as had difficult level 50 (minimal for quiz)
We have tried to follow documentation. What did we do wrong?

**Comment by semteacher** [comment]
I have a working solution which provide to me expected results. That only notice that this solution have not very "clearly" code:
https://github.com/semteacher/moodle-mod_adaptivequiz/tree/apply-mod_quiz_workflov2
If you found it helpful - I can create a pull request

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test?

**Comment by adamfranco** [comment]
Thank you for submitting this issue. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
