### ISSUE TITLE
Record question difficulty and test parameters for each attempt

### ISSUE THREAD

**Issue by adamfranco** [middlebury/moodle-mod_adaptivequiz#5]
Currently the attempt review summary has to look at the question's ability tags and setting on the test when displaying how the result was calculated. If a question's difficulty is modified or the test parameters change then the report will not match the summary score.

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test? 
khalid.kabchi@gmail.com

**Comment by adamfranco** [comment]
This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
