### ISSUE TITLE
Issues with unit test: mod_adaptivequiz_locallib_testcase for Moodle v3.6

### ISSUE THREAD

**Issue by sebasgraciavalderrama** [middlebury/moodle-mod_adaptivequiz#58]
Hello!

My name is Sebastián and I work as a developer for Blackboard - Open LMS Moodle team.

Recently we have discovered a strange behaviour with one of the test in mod_adaptivequiz. Please read the following comment:

The test `mod_adaptivequiz_locallib_testcase::test_adaptivequiz_complete_attempt`  is giving the following output:

########################################################################
vendor/bin/phpunit mod/adaptivequiz/tests/locallib_test.php
Moodle 3.6.3 (Build: 20190311), 953c924510701d711300aace97762eb41d7b20b6
Php: 7.1.20.1.16.04.1.1, mysqli: 5.7.23-0ubuntu0.16.04.1, OS: Linux 4.4.0-116-generic x86_64
PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

..............RThe instance of this module does not exist
..........                                         25 / 25 (100%)

Time: 36.63 seconds, Memory: 82.00MB

There was 1 risky test:

1) mod_adaptivequiz_locallib_testcase::test_adaptivequiz_complete_attempt
This test printed output: The instance of this module does not exist

To re-run:
 vendor/bin/phpunit "mod_adaptivequiz_locallib_testcase" mod/adaptivequiz/tests/locallib_test.php

OK, but incomplete, skipped, or risky tests!
Tests: 25, Assertions: 37, Risky: 1.`
########################################################################

If you have any questions or concerns, feel free to reach out to me at sebastian.gracia@blackboard.com :)

**Comment by adamfranco** [comment]
Thank you for submitting this issue. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.
